# .github/workflows/check-compliance-release.yml

name: Newer Check for new ComplianceAsCode Release

on:
  schedule:
    - cron: '0 2 5 * *' # Runs on the 5th of every month
  workflow_dispatch: {}

env:
  # Configure repository to watch
  TARGET_REPO: "ComplianceAsCode/content" 
  STATE_FILE: ".github/state/last_seen_release"

  # Space-separated list of role names to copy from the 'out' directory
  # Examples: rhel9_stig, rhel9_cis, rhel9_anssi
  ROLES_TO_COPY: "rhel9_cui rhel9_stig rhel9_cis"
  ROLES_DIR: "roles"
  
  # Ansible Galaxy metadata
  GALAXY_NAMESPACE: "dperrone_test"
  GALAXY_NAME: "compliance_roles"

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Get latest release tag from ComplianceAsCode
        id: get_release
        run: |
          TAG=$(curl -s -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ env.TARGET_REPO }}/releases/latest" | jq -r .tag_name)
          echo "Latest release on ${{ env.TARGET_REPO }} is: $TAG"
          echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Get last processed tag from file
        id: get_last_tag
        run: |
          if [ -f "${{ env.STATE_FILE }}" ]; then
            echo "last_tag=$(cat ${{ env.STATE_FILE }})" >> $GITHUB_OUTPUT
          else
            echo "last_tag=''" >> $GITHUB_OUTPUT
          fi
      
      - name: Compare tags
        id: compare
        run: |
          echo "Latest tag on remote: ${{ steps.get_release.outputs.latest_tag }}"
          if [ "${{ steps.get_release.outputs.latest_tag }}" != "${{ steps.get_last_tag.outputs.last_tag }}" ]; then
            echo "✅ New release found. Proceeding with build."
            echo "new_release_found=true" >> $GITHUB_OUTPUT
            # Also set version outputs for later steps
            echo "tag=${{ steps.get_release.outputs.latest_tag }}" >> $GITHUB_OUTPUT
            echo "version=${{ steps.get_release.outputs.latest_tag#v }}" >> $GITHUB_OUTPUT
          else
            echo "No new release. Exiting."
            echo "new_release_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.compare.outputs.new_release_found == 'true'
        run: |
          echo "Installing dependencies ..."
          sudo apt-get update
          sudo apt-get install -y git cmake make openscap-common openscap-scanner python3-yaml \
          python3-setuptools python3-pip python3-github libxml2-utils xsltproc

      - name: Clone and build ComplianceAsCode
        id: build
        run: |
          echo "Clonging ComplianceAsCode/content repository"
          git clone https://github.com/ComplianceAsCode/content
          cd content

          echo "Building the RHEL9 product"
          ./build_product rhel9

          echo "Generating Ansible roles ..."
          export PYTHONPATH=.
          utils/ansible_playbook_to_role.py --dry-run out --build-playbooks-dir build/ansible

          echo "Build complete. Output is located in content/out"

      - name: Assemble the Ansible collection
        id: assemble
        if: steps.compare.outputs.new_release_found == 'true'
        run: |
          echo "Assembling Ansible Collection..."
          mkdir -p ${{ env.ROLES_DIR }}
          rm -rf ${{ env.ROLES_DIR }}/*
          
          for role in ${{ env.ROLES_TO_COPY }}; do
            if [ -d "content-build/out/$role" ]; then
              echo "Copying $role..."
              cp -r "content-build/out/$role" "${{ env.ROLES_DIR }}/"
            else
              echo "WARNING: Role '$role' not found in build output."
            fi
          done
          
          GALAXY_VERSION="${{ steps.compare.outputs.version }}"
          echo "Updating galaxy.yml with version $GALAXY_VERSION"
          cat <<EOF > galaxy.yml
          namespace: ${{ env.GALAXY_NAMESPACE }}
          name: ${{ env.GALAXY_NAME }}
          version: $GALAXY_VERSION
          readme: README.md
          authors: [- Auto-generated by GitHub Actions]
          description: Ansible Collection for ComplianceAsCode roles.
          license: [Apache-2.0]
          tags: [security, compliance, stig, cis]
          dependencies: {}
          repository: ${{ github.server_url }}/${{ github.repository }}
          homepage: ${{ github.server_url }}/${{ github.repository }}
          issues: ${{ github.server_url }}/${{ github.repository }}/issues
          EOF

          echo "Creating meta/runtime.yml..."
          mkdir -p meta
          cat <<EOF > meta/runtime.yml
          ---
          requires_ansible: '>=2.9.10'
          EOF
          
          echo "Creating collection tarball..."
          TARBALL_NAME="${{ env.GALAXY_NAMESPACE }}-${{ env.GALAXY_NAME }}-${GALAXY_VERSION}.tar.gz"
          tar -czf $TARBALL_NAME ${{ env.ROLES_DIR }}/ galaxy.yml meta/
          
          # Output the tarball name for the release step
          echo "tarball_name=$TARBALL_NAME" >> $GITHUB_OUTPUT

      - name: Update state file
        if: steps.compare.outputs.new_release_found == 'true'
        run: |
          echo "Updating state file to ${{ steps.compare.outputs.tag }}"
          mkdir -p $(dirname "${{ env.STATE_FILE }}")
          echo "${{ steps.compare.outputs.tag }}" > ${{ env.STATE_FILE }}

      - name: 💾 Commit Ansible Collection and state file
        if: steps.compare.outputs.new_release_found == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Ansible Collection to ${{ steps.compare.outputs.tag }}"
          file_pattern: "${{ env.ROLES_DIR }} galaxy.yml meta/ ${{ env.STATE_FILE }}"

      - name: Create GitHub release
        if: steps.compare.outputs.new_release_found == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.compare.outputs.tag }}
          name: "Ansible Collection ${{ steps.compare.outputs.tag }}"
          files: ${{ steps.assemble.outputs.tarball_name }}
          body: |
            Automated release of the Ansible Collection.
            Based on ComplianceAsCode release: ${{ steps.compare.outputs.tag }}